apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ems-api
  template:
    metadata:
      labels:
        app: ems-api
    spec:
      containers:
      - name: ems-api
        image: amunipelumi/ems-k8s:v1.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        envFrom:
          - secretRef:
              name: envs
        ports:
        - containerPort: 8000
        command: ["/bin/sh", "-c", "alembic upgrade head && uvicorn ems_api.main:app --host 0.0.0.0 --port 8000"]

---

apiVersion: v1
kind: Service
metadata:
  name: ems-api
spec:
  type: NodePort
  selector:
    app: ems-api
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30116
