apiVersion: v1
kind: Secret
metadata:
  name: envs
type: Opaque
data:
  REDIS_PASSWORD: RmFsc2U==
  RABBITMQ_DEFAULT_USER: RmFsc2U==  
  RABBITMQ_DEFAULT_PASS: RmFsc2U==
  MONGO_INITDB_ROOT_USERNAME: RmFsc2U==
  MONGO_INITDB_ROOT_PASSWORD: RmFsc2U==
  POSTGRES_USER: RmFsc2U==
  POSTGRES_PASSWORD: RmFsc2U==
  POSTGRES_DB: RmFsc2U=
  TEST_MODE: RmFsc2U=
  SECRET_KEY: RmFsc2U===
  ALGORITHM: RmFsc2U==
  EXPIRE_MIN: RmFsc2U==
  EXPIRE_DAYS: RmFsc2U===
  DB_USERNAME: RmFsc2U==
  DB_HOSTNAME: RmFsc2U==
  DB_PASS: RmFsc2U==
  DB_PORT: RmFsc2U===
  DB_NAME: RmFsc2U=
  REDIS_PASS: RmFsc2U==
  REDIS_HOST: RmFsc2U==
  REDIS_PORT: RmFsc2U===
  REDIS_DB: RmFsc2U===
  RMQ_PORT: RmFsc2U===
  RMQ_USERNAME: RmFsc2U==
  RMQ_PASSWORD: RmFsc2U==
  RMQ_ADDRESS: RmFsc2U==
  MDB_HOST: RmFsc2U===
  MDB_PORT: RmFsc2U==
  MDB_NAME: RmFsc2U=
  MDB_COLL: RmFsc2U=
