"""adding indexes to users and events

Revision ID: 1a0dc51c41d8
Revises: 9933ca8e431c
Create Date: 2024-10-09 11:12:42.685077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a0dc51c41d8'
down_revision: Union[str, None] = '9933ca8e431c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('id_idx', 'events', ['id'], unique=False)
    op.create_index('id_email_idx', 'users', ['id', 'email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id_email_idx', table_name='users')
    op.drop_index('id_idx', table_name='events')
    # ### end Alembic commands ###
