"""02 linking event and venue

Revision ID: 4c0875eeb5de
Revises: 923e566df11a
Create Date: 2024-09-19 15:49:51.557589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0875eeb5de'
down_revision: Union[str, None] = '923e566df11a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('event_id', sa.Integer(), nullable=False))
    op.drop_constraint('venues_address_key', 'venues', type_='unique')
    op.create_foreign_key(None, 'venues', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.create_unique_constraint('venues_address_key', 'venues', ['address'])
    op.drop_column('venues', 'event_id')
    # ### end Alembic commands ###
