"""03 linking event and venue

Revision ID: f2cd6e420f08
Revises: 4c0875eeb5de
Create Date: 2024-09-19 16:04:13.742017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2cd6e420f08'
down_revision: Union[str, None] = '4c0875eeb5de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_venue_id_fkey', 'events', type_='foreignkey')
    op.drop_column('events', 'venue_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('events_venue_id_fkey', 'events', 'venues', ['venue_id'], ['id'])
    # ### end Alembic commands ###
